# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StudyLogin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StudyLogin
  pod 'naveridlogin-sdk-ios'
  pod 'Alamofire'
  pod 'AlamofireImage', '~> 4.1'
  pod 'KakaoSDKAuth'  # 사용자 인증
  pod 'KakaoSDKUser'  # 카카오 로그인, 사용자 관리

end
